# Generated by Django 3.2.4 on 2021-07-22 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja_app', '0004_alter_itensmodel_vendedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='itensmodel',
            name='imagem',
            field=models.ImageField(default='img/no_foto_item.png', upload_to='', verbose_name='Imagem do Produto'),
        ),
    ]
