# Generated by Django 3.2.4 on 2021-07-27 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja_app', '0005_itensmodel_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itensmodel',
            name='imagem',
            field=models.ImageField(upload_to='', verbose_name='Imagem do Produto'),
        ),
    ]
