# Generated by Django 3.2.4 on 2021-09-07 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loja_app', '0010_alter_itensmodel_imagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ManyToManyField(to='loja_app.ItensModel')),
            ],
        ),
    ]
