# Generated by Django 3.2.4 on 2021-09-19 03:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loja_app', '0010_alter_itensmodel_imagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItemModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_compra', models.IntegerField(verbose_name='Quantidade do item no carrinho')),
                ('time_item_added', models.DateTimeField(auto_now=True)),
                ('loja_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loja_app.itensmodel')),
            ],
            options={
                'db_table': 'cart_item',
            },
        ),
        migrations.CreateModel(
            name='CartLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cartitem_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart_app.cartitemmodel')),
            ],
            options={
                'db_table': 'cart_model_has_cart_item',
            },
        ),
        migrations.CreateModel(
            name='CartModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_cart_added', models.DateTimeField(auto_now=True)),
                ('cart_item', models.ManyToManyField(through='cart_app.CartLink', to='cart_app.CartItemModel')),
                ('comprador', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cart_model',
            },
        ),
        migrations.AddField(
            model_name='cartlink',
            name='cartmodel_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart_app.cartmodel'),
        ),
    ]
