# Generated by Django 3.2.4 on 2021-10-02 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartlink',
            old_name='cartitem_id',
            new_name='cartitem',
        ),
        migrations.RenameField(
            model_name='cartlink',
            old_name='cartmodel_id',
            new_name='cartmodel',
        ),
    ]
