# Generated by Django 3.2.4 on 2021-09-07 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja_app', '0010_alter_itensmodel_imagem'),
        ('cart_app', '0002_cartmodel_comprador'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItemModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(default=1, verbose_name='Quantidade do item no carrinho')),
                ('item', models.ManyToManyField(to='loja_app.ItensModel')),
            ],
        ),
        migrations.AlterField(
            model_name='cartmodel',
            name='item',
            field=models.ManyToManyField(to='cart_app.CartItemModel'),
        ),
    ]
