# Generated by Django 3.2.4 on 2021-09-07 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0003_auto_20210907_1620'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cartmodel',
            table='cart_model',
        ),
    ]
