# Generated by Django 3.2.4 on 2021-09-07 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0006_alter_cartitemmodel_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartmodel',
            old_name='item',
            new_name='cart_item',
        ),
    ]
