# Generated by Django 3.2.4 on 2021-09-08 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loja_app', '0010_alter_itensmodel_imagem'),
        ('cart_app', '0008_auto_20210908_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitemmodel',
            name='item',
            field=models.OneToOneField(default=7, on_delete=django.db.models.deletion.CASCADE, to='loja_app.itensmodel'),
        ),
    ]
