# Generated by Django 3.2.4 on 2021-09-09 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0010_cartitemmodel_comprador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitemmodel',
            name='quantidade',
            field=models.IntegerField(verbose_name='Quantidade do item no carrinho'),
        ),
    ]
