# Generated by Django 3.2.4 on 2021-09-09 16:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cart_app', '0011_alter_cartitemmodel_quantidade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitemmodel',
            name='comprador',
        ),
        migrations.AlterField(
            model_name='cartmodel',
            name='comprador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
