# Generated by Django 3.2.4 on 2021-09-09 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loja_app', '0010_alter_itensmodel_imagem'),
        ('cart_app', '0013_alter_cartmodel_comprador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartmodel',
            name='cart_item',
        ),
        migrations.AddField(
            model_name='cartmodel',
            name='cart_item',
            field=models.OneToOneField(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='loja_app.itensmodel'),
        ),
        migrations.DeleteModel(
            name='CartItemModel',
        ),
    ]
