# Generated by Django 3.2.4 on 2021-09-09 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loja_app', '0010_alter_itensmodel_imagem'),
        ('cart_app', '0014_auto_20210909_1613'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItemModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_compra', models.IntegerField(verbose_name='Quantidade do item no carrinho')),
                ('loja_item', models.OneToOneField(default=7, on_delete=django.db.models.deletion.CASCADE, to='loja_app.itensmodel')),
            ],
            options={
                'db_table': 'cart_item',
            },
        ),
    ]
