# Generated by Django 3.2.4 on 2021-09-09 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0015_cartitemmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartmodel',
            name='cart_item',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cart_app.cartitemmodel'),
        ),
    ]
