# Generated by Django 3.2.4 on 2021-09-09 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0016_alter_cartmodel_cart_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartmodel',
            name='cart_item',
        ),
        migrations.AddField(
            model_name='cartmodel',
            name='cart_item',
            field=models.ManyToManyField(default=1, to='cart_app.CartItemModel'),
        ),
    ]
