# Generated by Django 3.2.4 on 2021-09-09 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loja_app', '0010_alter_itensmodel_imagem'),
        ('cart_app', '0017_auto_20210909_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitemmodel',
            name='loja_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loja_app.itensmodel'),
        ),
    ]
