# Generated by Django 3.2.4 on 2021-09-09 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0018_alter_cartitemmodel_loja_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartmodel',
            name='cart_item',
            field=models.ManyToManyField(to='cart_app.CartItemModel'),
        ),
    ]
