# Generated by Django 3.2.4 on 2021-09-14 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0019_alter_cartmodel_cart_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitemmodel',
            name='time_item_added',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='cartmodel',
            name='time_cart_added',
            field=models.TimeField(auto_now=True),
        ),
    ]
