# Generated by Django 3.2.4 on 2021-07-12 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itensmodel',
            old_name='Descrição do Item!',
            new_name='descricao',
        ),
        migrations.RenameField(
            model_name='itensmodel',
            old_name='Nome do Item',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='itensmodel',
            old_name='Quantidade de Itens',
            new_name='quantidade',
        ),
        migrations.RenameField(
            model_name='itensmodel',
            old_name='Valor do Item',
            new_name='valor',
        ),
    ]
