# Generated by Django 3.2.4 on 2021-07-11 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_auto_20210710_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='first_name',
            field=models.CharField(default='M', max_length=255, verbose_name='Primeiro nome'),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='last_name',
            field=models.CharField(default='L', max_length=255, verbose_name='Sobrenome'),
        ),
    ]
