# Generated by Django 3.2.4 on 2021-07-13 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='is_seller',
            field=models.BooleanField(default=False),
        ),
    ]
